Version 2.0

---
Children:
- Children:
  - Children:
    - Children: []
      Properties:
        Output Channel (Solenoid): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['0', '1', '2', '3', '4', '5', '6', '7']
          default: '0'
          name: Output Channel (Solenoid)
          validators: [Solenoid]
          value: '0'
        Output PCM (Solenoid): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
            '12', '13', '14', '15', '16', '17', '18', '19', '20']
          default: '0'
          name: Output PCM (Solenoid)
          validators: [Solenoid]
          value: '0'
      Base: Solenoid
      Name: ShiftingPiston
    Properties:
      Send to SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Send to SmartDashboard, validators: null, value: false}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: OperatorControl}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: Drivetrain
  - Children: []
    Properties:
      Send to SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Send to SmartDashboard, validators: null, value: false}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: Vision
  - Children: []
    Properties:
      Send to SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Send to SmartDashboard, validators: null, value: false}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: Pixy
  - Children:
    - Children: []
      Properties:
        PCM ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
            '12', '13', '14', '15', '16', '17', '18', '19', '20']
          default: '0'
          name: PCM ID
          validators: [PCMCompID]
          value: '0'
      Base: Compressor
      Name: Compressor
    - Children: []
      Properties:
        Input Channel (Analog): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['0', '1', '2', '3', '4', '5', '6', '7']
          default: '0'
          name: Input Channel (Analog)
          validators: [AnalogInput]
          value: '0'
      Base: Analog Input
      Name: Pressure Gauge
    Properties:
      Send to SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Send to SmartDashboard, validators: null, value: false}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: Pneumatics
  - Children:
    - Children: []
      Properties:
        Output Channel (PWM): !!robotbuilder.data.properties.ChoicesProperty
          choices: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
            '12', '13', '14', '15', '16', '17', '18', '19']
          default: '0'
          name: Output Channel (PWM)
          validators: [PWMOutput]
          value: '0'
      Base: Servo
      Name: HoodServo
    Properties:
      Send to SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Send to SmartDashboard, validators: null, value: false}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: Shooter
  - Children:
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id001 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
            '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
            '23', '24', '25', '26', '27', '28', '29', '30', '31']
          default: '2'
          name: CAN ID
          validators: &id002 [CANID]
          value: '5'
      Base: Talon SRX
      Name: StageOne
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '2'
          name: CAN ID
          validators: *id002
          value: '6'
      Base: Talon SRX
      Name: StageTwo
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '2'
          name: CAN ID
          validators: *id002
          value: '7'
      Base: Talon SRX
      Name: StageThree
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '2'
          name: CAN ID
          validators: *id002
          value: '8'
      Base: Talon SRX
      Name: StageFour
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '2'
          name: CAN ID
          validators: *id002
          value: '9'
      Base: Talon SRX
      Name: StageFive
    - Children: []
      Properties:
        Input Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: &id003 ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10',
            '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
            '23', '24', '25']
          default: '0'
          name: Input Channel (Digital)
          validators: &id004 [DigitalChannel]
          value: '0'
      Base: Digital Input
      Name: SensorOne
    - Children: []
      Properties:
        Input Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id003
          default: '0'
          name: Input Channel (Digital)
          validators: *id004
          value: '1'
      Base: Digital Input
      Name: SensorTwo
    - Children: []
      Properties:
        Input Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id003
          default: '0'
          name: Input Channel (Digital)
          validators: *id004
          value: '2'
      Base: Digital Input
      Name: SensorThree
    - Children: []
      Properties:
        Input Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id003
          default: '0'
          name: Input Channel (Digital)
          validators: *id004
          value: '3'
      Base: Digital Input
      Name: SensorFour
    - Children: []
      Properties:
        Input Channel (Digital): !!robotbuilder.data.properties.ChoicesProperty
          choices: *id003
          default: '0'
          name: Input Channel (Digital)
          validators: *id004
          value: '4'
      Base: Digital Input
      Name: SensorFive
    - Children: []
      Properties:
        CAN ID: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id001
          default: '2'
          name: CAN ID
          validators: *id002
          value: '11'
      Base: Talon SRX
      Name: Kicker
    Properties:
      Send to SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Send to SmartDashboard, validators: null, value: false}
      Default command parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Default command parameters
        validators: null
        value: []
      Default Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Default Command, type: Command, validators: null, value: None}
      Constants: !!robotbuilder.data.properties.ConstantsProperty
        default: []
        name: Constants
        validators: null
        value: []
    Base: Subsystem
    Name: BallIntake
  Properties: {}
  Base: Subsystems
  Name: Subsystems
- Children:
  - Children:
    - Children: []
      Properties:
        Joystick: !!robotbuilder.data.properties.ParentProperty {default: parent,
          name: Joystick, validators: null, value: RightJoystick}
        Parameters: !!robotbuilder.data.properties.ParametersProperty
          default: []
          name: Parameters
          validators: null
          value: []
        Button: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id005 ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11',
            '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
            '24', '25', '26', '27', '28', '29', '30', '31', '32']
          default: '1'
          name: Button
          validators: null
          value: '1'
        Command: !!robotbuilder.data.properties.TypeSelectionProperty
          default: None
          name: Command
          type: Command
          validators: &id006 [TypeDropdownSelected]
          value: FollowBall
        When to Run: !!robotbuilder.data.properties.ChoicesProperty
          choices: &id007 [whileHeld, whenPressed, whenReleased]
          default: whileHeld
          name: When to Run
          validators: null
          value: whileHeld
      Base: Joystick Button
      Name: Trigger
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: &id008 ['0', '1', '2', '3', '4', '5']
        default: 1
        name: Number
        validators: &id009 [Joystick]
        value: '0'
    Base: Joystick
    Name: RightJoystick
  - Children:
    - Children: []
      Properties:
        Joystick: !!robotbuilder.data.properties.ParentProperty {default: parent,
          name: Joystick, validators: null, value: LeftJoystick}
        Parameters: !!robotbuilder.data.properties.ParametersProperty
          default: []
          name: Parameters
          validators: null
          value: []
        Button: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id005
          default: '1'
          name: Button
          validators: null
          value: '1'
        Command: !!robotbuilder.data.properties.TypeSelectionProperty
          default: None
          name: Command
          type: Command
          validators: *id006
          value: CenterAndShoot
        When to Run: !!robotbuilder.data.properties.ChoicesProperty
          choices: *id007
          default: whileHeld
          name: When to Run
          validators: null
          value: whileHeld
      Base: Joystick Button
      Name: ShootTrigger
    Properties:
      Number: !!robotbuilder.data.properties.ChoicesProperty
        choices: *id008
        default: 1
        name: Number
        validators: *id009
        value: '1'
    Base: Joystick
    Name: LeftJoystick
  Properties: {}
  Base: OI
  Name: Operator Interface
- Children:
  - Children: []
    Properties:
      Autonomous Selection: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Autonomous Selection, validators: null, value: false}
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Run When Disabled: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Run When Disabled, validators: null, value: false}
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: true}
    Base: Command
    Name: Autonomous Command
  - Children: []
    Properties:
      Autonomous Selection: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Autonomous Selection, validators: null, value: false}
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Run When Disabled: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Run When Disabled, validators: null, value: false}
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: Drivetrain}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
    Base: Command
    Name: OperatorControl
  - Children: []
    Properties:
      Autonomous Selection: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Autonomous Selection, validators: null, value: false}
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Run When Disabled: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Run When Disabled, validators: null, value: false}
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
    Base: Command
    Name: FollowBall
  - Children: []
    Properties:
      Autonomous Selection: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Autonomous Selection, validators: null, value: false}
      Parameters: !!robotbuilder.data.properties.ParametersProperty
        default: []
        name: Parameters
        validators: null
        value: []
      Run When Disabled: !!robotbuilder.data.properties.BooleanProperty {default: false,
        name: Run When Disabled, validators: null, value: false}
      Requires: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
        name: Requires, type: Subsystem, validators: null, value: None}
      Parameter presets: !!robotbuilder.data.properties.ParameterSetProperty
        default: []
        name: Parameter presets
        validators: null
        value: []
      Button on SmartDashboard: !!robotbuilder.data.properties.BooleanProperty {default: true,
        name: Button on SmartDashboard, validators: null, value: false}
    Base: Command
    Name: CenterAndShoot
  Properties: {}
  Base: Commands
  Name: Commands
Properties:
  Export Commands: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Commands, validators: null, value: true}
  Autonomous command parameters: !!robotbuilder.data.properties.ParametersProperty
    default: []
    name: Autonomous command parameters
    validators: null
    value: []
  Java Package: !!robotbuilder.data.properties.StringProperty {default: frc.robot,
    name: Java Package, validators: null, value: frc.robot}
  Use Default Java Package: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Use Default Java Package, validators: null, value: true}
  Team Number: !!robotbuilder.data.properties.IntegerProperty {default: 0, name: Team
      Number, validators: null, value: 3018}
  Export Subsystems: !!robotbuilder.data.properties.BooleanProperty {default: true,
    name: Export Subsystems, validators: null, value: true}
  Simulation World File: !!robotbuilder.data.properties.StringProperty {default: /usr/share/frcsim/worlds/GearsBotDemo.world,
    name: Simulation World File, validators: null, value: /usr/share/frcsim/worlds/GearsBotDemo.world}
  Wiring file location: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Computer\',
    extension: null, folder: true, name: Wiring file location, validators: null, value: 'C:\Users\Computer\'}
  Export Directory: !!robotbuilder.data.properties.FileProperty {default: 'C:\Users\Computer\FRCProjects',
    extension: null, folder: true, name: Export Directory, validators: null, value: 'C:\Users\Computer\FRCProjects'}
  Autonomous Command: !!robotbuilder.data.properties.TypeSelectionProperty {default: None,
    name: Autonomous Command, type: Command, validators: null, value: Autonomous Command}
Base: Robot
Name: NordicStorm2020
