// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.controller.PIDController;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.Robot;
import frc.robot.subsystems.Drivetrain;

/**
 *
 */
public class AtMaxSpeed extends PathSection {


    double speed;
    public AtMaxSpeed(double speed) {
        this.speed=speed;
    }

    
    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return true;
    }

    

    @Override
    public double getRequestedStartSpeed() {
        return speed;
    }
    @Override
    public double getProvidedEndSpeed() {
        return speed;
    }

    @Override
    public void finalizeForPath(PathSection previous, PathSection next) {
    }
    @Override
    public double modifyAngle(double oldAngle) {
        return oldAngle;
    }
    
}
