// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import frc.robot.Robot;
import frc.robot.subsystems.*;

/**
 *
 */
public class AutoSnowThrower extends AutoWithInit {

    public AutoSnowThrower() {
        requires(Robot.drivetrain);
    
    }
    @Override
    protected void initialize() {
        //Robot.drivetrain.resetHeading();
        Robot.shooter.setAutoSeekHeading(false, 0);
        Robot.shooter.setAutoTargetSeek(false, 5);
    }
    @Override
    public void initializeCommands(){
        double startAng = 36;
        //addSequential(new SetIntakeRunning(true));
        MultiPartPath path = new MultiPartPath(startAng);
        path.addShooterVisionCenter(15);
        /*path.addShooterSpeedSet(1830, 35);
        path.addStraight(8.5, false);
        path.addRawArc(-33, 0.051, 0.4025, false);
        path.addShooterTargettingSet(true, 19, false, 0);
        path.addBallGrab(false, 0.5);
        path.addRawArc(272, -0.02, 0.2325, false, true);
        path.addStop();
        path.addBallShoot(1);
        path.addStop(500);
        path.addShooterTargettingSet(false, 0, false, 0);
        path.addPivot(200, 0.25, false, false);
        path.addShooterSpeedSet(2200, 25);
        path.addRawArc(105, 0.13, 0.4025, false);
        path.addShooterTargettingSet(true, -15, false, 0);
        path.addBallGrab(false, 0.5);
        path.addStop();
        path.addStraight(1, true, 90, 0.5);
        //path.addRawArc(100, 0.06, 0.2325, false, true);
        path.addStop();
        path.addBallShoot(1);
        path.addStop(500);
        path.addRawArc(40, 0.16, 0.4025, false, true);
        path.addShooterTargettingSet(true, -4, false, 0);
        path.addShooterSpeedSet(2400, 25);
        path.addPivot(90, 0.25, true, false);
        path.addBallGrab(false, 0.5);
        path.addStraight(0.7, true, 90, 0.5);
        path.addStop();
        path.addBallShoot(1);*/





        //addSequential(new SetIntakeRunning(true));
        addSequential(path.finalizePath());

    }
    @Override
    protected void end() {
        Robot.ballIntake.setLongRunningIntake(false);
        Robot.shooter.setAutoSeekHeading(false, 0);
    }
    @Override
    protected void interrupted(){
        end();
    }   
}