
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;
import frc.robot.Util;
import frc.robot.subsystems.Drivetrain;

/**
 *
 */
public class DriveDistancePath extends PathSection {

    double leftTargetPos;
    double rightTargetPos;

    double totalDistance;
    boolean reversed;
    double startSpeed;
    double mainSpeed;
    double endSpeed;

    boolean done = false;
    double minSpeed = 0.1;// 0.25
    double keepStraightAngle=0;

    /**
     * 
     * @param distance distance in encoder units. 913=1 ft
     * @param speed    speed%. Between -1-1. Negative means backward
     */
    public DriveDistancePath(double distance, double speed) {
        if (speed < 0) {
            distance *= -1;
        }
        reversed = speed < 0;

        this.totalDistance = distance;
        this.mainSpeed = speed;
        requires(Robot.drivetrain);

    }

    @Override
    protected void initialize() {
        Robot.drivetrain.setEncMode(true);
        Robot.drivetrain.setSuperPMode(true);
        // Robot.drivetrain.resetEncoderPositions();
        leftTargetPos = Robot.drivetrain.getLeftEncoderDistance() - totalDistance;
        rightTargetPos = Robot.drivetrain.getRightEncoderDistance() + totalDistance;
        Robot.drivetrain.setOutsideControl(true);
        done = false;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        double leftPos = Robot.drivetrain.getLeftEncoderDistance();
        double rightPos = Robot.drivetrain.getRightEncoderDistance();
        double distanceAway=Math.min(getDistanceAway(leftPos, leftTargetPos, !reversed), getDistanceAway(rightPos, rightTargetPos, reversed));
        double percentDone=1-(distanceAway/Math.abs(totalDistance));
        double leftSpeed = calcSpeedNeeded(percentDone);
        // System.out.println("right");
        double rightSpeed = calcSpeedNeeded(percentDone);

        double currentAngle=Robot.drivetrain.getAngle();
        double angleDiff=Drivetrain.angleDiff(currentAngle, keepStraightAngle);
        double adjustment=Util.absClamp(angleDiff*0.01, leftSpeed);//left and right are the same at this point
        leftSpeed+=adjustment;
        rightSpeed-=adjustment;
        System.out.println("err:"+angleDiff);

        System.out.println("adj:"+adjustment);

        System.out.println("left:"+leftSpeed);
        System.out.println("right:"+rightSpeed);

        Robot.drivetrain.tankDriveDirect(-leftSpeed, rightSpeed);
        if (distanceAway < 0) {
            done = true;
        }
    }

    private double getDistanceAway(double currentPos, double targetPos, boolean reversed) {
        double distance;
        if (reversed) {
            distance = currentPos - targetPos;

        } else {
            distance = targetPos - currentPos;

        }
        // System.out.println("getDistAway:"+distance);

        return distance;
    }
    private double calcSpeedNeeded(double currentPercentdone){
        double driveSpeed = currentPercentdone * endSpeed;
        if (Math.abs(driveSpeed) < minSpeed) {
            driveSpeed = Math.copySign(minSpeed, driveSpeed);
        }
        return driveSpeed;
    }
    

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        return done;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        // Robot.drivetrain.setSuperPMode(false);
        // Robot.drivetrain.setOutsideControl(false);
        // Robot.drivetrain.drive(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }

    @Override
    public double modifyAngle(double oldAngle) {
        keepStraightAngle=oldAngle;
        return oldAngle;
    }
    @Override
    public double getRequestedStartSpeed() {
        return mainSpeed;
    }
    
    @Override
    public void finalizeForPath(PathSection previous, PathSection next) {
        endSpeed = next.getRequestedStartSpeed();
    }

    @Override
    public double getProvidedEndSpeed() {
        return 0;
    }
}
